on:
  push:
    branches:
      - master
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy via ssh
      uses: appleboy/scp-action@master
      with:
        source : practiceForAlgorithm/
        target : airflow/dags
        host: ${{ secrets.HOST }}
        username : ${{ secrets.SSH_USER }}
        key : ${{ secrets.PRIVATE_KEY }}
